function RPR_A_RECEBER
return .t.  
function RPR_GERAL_R
return .t.
function RPR_CLIENTE
return .t.
function INC_CONTRATO
return .t.
function ALT_CONTRATO
return .t.
//function CON_CONTRATO

//function REA_TARIFA
//return .t.
function PRINT_CAPA
return .t.
function RPR_PREV_R
return .t.
function RPR_GERAL_
return .t.
function RPR_CLIENT
return .t.
function RPR_FAT_CA
return .t.
function RPR_RELF1
return .t.
function RPR_NAO_FA
return .t.
function RPR_FC1_CO
return .t.
function RPR_BLOQ_C
return .t.
function RPR_ETQFAT
return .t.
function RPR_SEAGRA
return .t.
function RPR_NALCO
return .t.
function RPR_NOTA_D
return .t.
function RPR_FR3060
return .t.
function RPR_FEMBAY
return .t.
function RPR_FAT_DE
return .t.
function RPR_CHECK
return .t.
function RPR_CHK_CO
return .t.
function RPR_CHK2_C
return .t.
function RPR_CTRL_F
return .t.
function RPR_FAT_MB
return .t.
function RPR_FATXRE
return .t.
function EXPSXP_CTE
return .t.
function EXPSXP_FAT
return .t.
function RPR_ICMS_C
return .t.
function RPR_ICMS_1
return .t.
function RPR_ICMS_3
return .t.
function RPR_ICMS_2
return .t.
function RPR_CONERR
return .t.
function RPR_CTRBIR
return .t.
function RPR_CTRBAN
return .t.
function RPR_CTRBDE
return .t.
function RPR_SESTIN
return .t.
function RPR_TERM_A
return .t.
function RPR_TERM_F
return .t.
function DIRF08
return .t.
function SEFIP
return .t.
function SEPD
return .t.
function SINTEGRA
return .t.
function RPR_NF_PEN
return .t.
function RPR_NF_ENT
return .t.
function RPR_RAZNF
return .t.
function RPR_COMPRO
return .t.
function RPR_OCO_PE
return .t.
function RPR_NOTA_E
return .t.
function RPR_CON_RE
return .t.

function RPR_CTRBTE
return .t.
function RPR_CTRBTC
return .t.
function RPR_CTRBTR
return .t.
function RPR_CTRBTA
return .t.
function RPR_EXT_PE
return .t.
function RPR_MANEXP
return .t.
function RPR_RAUTON
return .t.
function RPR_ARQDEG
return .t.
function RPR_REL_F2
return .t.
function RPR_REL_F3
return .t.
function RPR_PEGASU
return .t.
function RPR_PERF
return .t.
function RPR_CTRB_P
return .t.
function RPR_TRACK_
return .t.
function RPR_MANIF_
return .t.
function RPR_CTRC_E
return .t.
function RPR_SASSMA
return .t.
function RPR_GER_RI
return .t.
function RPR_AEF
return .t.
function RPR_PVI
return .t.
function RPR_MVR
return .t.
function RPR_R4080
return .t.
function RPR_APURA_
return .t.
function RPR_ACOMP_
return .t.
function RPR_TEMPO_
return .t.
function RPR_ONU_TR
return .t.
function RPR_TERMO2
return .t.
function GERA_TOKEN
return .t.
function RPR_NOVO_R
return .t.
function RPR_DESP_M
return .t.
function RPR_SFP_VI
return .t.
function RPR_PENDV
return .t.
function RPR_VIAEX
return .t.
function RPR_AGENDA
return .t.
function RPR_MOTOR1
return .t.
function RPR_VSUS
return .t.
function RPR_CAR_OP
return .t.
function RPR_MOT_OP
return .t.
function RPR_KM_CAR
return .t.
function RPR_REG_OC
return .t.
function RPR_GER_CT
return .t.
function RPR_OCUP_C
return .t.
function RPR_JORNAD
return .t.
function RPR_TPEV
return .t.
function RPR_BAFOME
return .t.
function RPR_ATUAL_
return .t.
function RPR_REFEIC
return .t.
function RPR_ENTREJ
return .t.

function RPR_ROTAS
return .t.
function RPR_TTPV
return .t.
function RPR_RRC_PE
return .t.
function RPR_RRC_BX
return .t.
function RPR_CCI_PE
return .t.
function RPR_CCI_PA
return .t.
function RPR_ROC_PE
return .t.
function RPR_ROC_BX
return .t.
function RPR_ROC_EM
return .t.
function LIMITA_DAT
return .t.

function RPR_MULTAS
return .t.
function RPR_ABAST
return .t.

function RPR_DAV
return .t.
function RPR_RECEIT
return .t.
 
function RPR_COM_GE
return .t.
function RPR_2COM_G
return .t.
function RPR_CPP
return .t.
function RPR_CON_EM
return .t.
function RPR_CUSTO_
return .t.
function BUSCA_FCAR
return .t.
function RPR_SEAGRAM
return .t.
function RPR_FAT_DET
return .t.
function RPR_CHK_COGNIS
return .t.
function RPR_CHK2_COGNIS
return .t.
function ARQ_BBRASIL
return .t.
function IMP_CONTRATO
return .t.
function RPR_FATXREC
return .t.
function RPR_ICMS_CD
return .t.
function RPR_CONERRO
return .t.
function RPR_CTRBIRRF
return .t.
function RPR_CTRBANUAL
return .t.
function RPR_SESTINSS
return .t.
function RPR_TERM_ABERT
return .t.
function RPR_TERM_FECH
return .t.
function RPR_CTRBDESP
return .t.
function RPR_OCO_PENDENTE
return .t.
function RPR_NOTA_EMB
return .t.

function RPR_CTRBTRES
return .t.
function RPR_CTRBTAUT
return .t.
function RPR_EXT_PEDAGIO
return .t.
function RPR_RAUTONOMO
return .t.
function RPR_PEGASUS
return .t.
function RPR_CTRB_PPS
return .t.
function RPR_TRACK_NOTA
return .t.

function RPR_GER_RISCO
return .t.
function RPR_APURA_IMPOSTO
return .t.
function RPR_TEMPO_ENTREGA
return .t.
function RPR_ONU_TRANSP
return .t.


function RPR_AGENDA_BASF
return .t.
function RPR_CAR_OPER
return .t.
function RPR_MOT_OPER
return .t.
function RPR_KM_CARRETA
return .t.
function RPR_REG_OCO
return .t.
function RPR_GER_CTRC
return .t.
function RPR_OCUP_CAR
return .t.
function RPR_JORNADA
return .t.
function RPR_BAFOMETRO
return .t.
function RPR_ATUAL_KM
return .t.
function RPR_REFEICAO
return .t.
function RPR_ENTREJORNADA
return .t.
function RPR_RRC_PEND
return .t.
function RPR_CCI_PEND
return .t.
function RPR_CCI_PAGO
return .t.
function RPR_ROC_PEND
return .t.
function RPR_ROC_EMIT
return .t.

function RPR_RECEITA
return .t.
function RPR_COM_GES
return .t.
function RPR_2COM_GES
return .t.
function RPR_CON_EMIT
return .t.
function RPR_CUSTO_CAR
return .t.

**************************
function LF_FCOPY
return .t.
function LF_FERASE
return .t.
function LF_ISFILE
return .t.
function LF_FOPEN
return .t.
function LF_FRENAME
return .t.
**************************

function CHCK_ANTCTRB
return .t.
function SC_NOTA_EMP
return .t.
function LIMITA_DATA
return .t.
function BUSCA_FCARRO
return .t.
function HELP_BANCOS
return .t.
function CSETEXCL
return .t.
function VIEW_CCCLIENT
return .t.